### ISSUE TITLE
Docker container error

### ISSUE THREAD

**Issue by xdubx** [cortezaproject/corteza-server-corredor#34]
```
 corredor:
    image: cortezaproject/corteza-server-corredor:2021.9.3
    volumes:
      - corredor:/corredor
    networks:
      - crmnet
    environment:
      CORREDOR_EXT_SEARCH_PATHS : corredor:/corredor/test-extension
      CORREDOR_ADDR: "localhost:50051"
      CORREDOR_DEBUG: "true"
```

Container starts with error

```
internal/modules/cjs/loader.js:796,
    throw err;,
    ^,
,
Error: Cannot find module '/corredor/ts-node',
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17),
    at Function.Module._load (internal/modules/cjs/loader.js:686:27),
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10),
    at internal/main/run_main_module.js:17:11 {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [],
}
```
